services:
  db:
    image: pgvector/pgvector:pg17
    container_name: pgvector17
    environment:
      POSTGRES_USER: tesis
      POSTGRES_PASSWORD: tesis
      POSTGRES_DB: tesis
    ports:
      - "5444:5432"   # usa 5433 en tu host para no chocar con PG local en 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
